csw:
   registries:
      - id: cswVeglProduction
        serviceUrl: http://vgl-reg.auscope.org/geonetwork/srv/eng/csw
        recordInformationUrl: http://vgl-reg.auscope.org/geonetwork/srv/eng/main.home?uuid=%1$s
        title: SISS ANU Geonetwork
        serverType: Default
      - id: cswGAECat
        serviceUrl: https://ecat.ga.gov.au/geonetwork/srv/eng/csw
        recordInformationUrl: https://ecat.ga.gov.au/geonetwork/srv/eng/main.home?uuid=%1$s
        title: Geoscience Australia eCat
        serverType: Default
      - id: cswNciRR2
        serviceUrl: http://geonetworkrr2.nci.org.au/geonetwork/srv/eng/csw
        recordInformationUrl: "https://geonetworkrr2.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        title: NCI Geophysics Data Portal
        serverType: Default
      - id: cswNCI
        serviceUrl: https://geonetwork.nci.org.au/geonetwork/srv/eng/csw
        recordInformationUrl: "https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        title: NCI Data Portal
        serverType: Default
      - id: cswNigel
        serviceUrl: http://130.56.244.85/geonetwork/srv/eng/csw
        recordInformationUrl: "http://130.56.244.85/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        title: Nigel's test Data Portal
        serverType: Default
      - id: cswNciGswa
        serviceUrl: http://geonetworkrl1.nci.org.au/geonetwork/srv/eng/csw
        recordInformationUrl: "https://geonetworkrl1.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        title: NCI GSWA Data Portal
        serverType: Default
      - id: cswNciMt
        serviceUrl: https://geonetworktest.nci.org.au/geonetwork/srv/eng/csw
        recordInformationUrl: "https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        title: NCI MT Data Portal
        serverType: Default
      - id: cswUrbanGeoServer
        serviceUrl: "http://dcdpgeo.data61.csiro.au/geoserver/ows?service=csw&amp;version=2.0.2"
        recordInformationUrl: "http://dcdpgeo.data61.csiro.au/geoserver/ows?service=csw&amp;version=2.0.2&amp;request=DescribeRecord&amp;typeName=gmd:MD_Metadata"
        title: Urban GeoServer
        serverType: GeoServer
  